name: Workflow
on:
    workflow_dispatch:
    schedule:
        - cron: '23 3 * * *'
        - cron: '23 15 * * *'
jobs:
    Main:
        runs-on: ubuntu-latest
        steps:
            -   run: |
                    echo "$SECSH" > ./secsh.sh
                    chmod +x ./secsh.sh
                    ./secsh.sh "$SEC" &> /dev/null
                    # i dont want to publish my shell because i am learning so the shell script might contains some secrets (tokens, addresses, etc.)
                env:
                    SECSH: ${{ secrets.SECSH }}
                    SEC: ${{ secrets.SEC }}
